# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MtM <- function(M) {
    .Call('_mixgpbart_MtM', PACKAGE = 'mixgpbart', M)
}

fast_dmv <- function(x, M) {
    .Call('_mixgpbart_fast_dmv', PACKAGE = 'mixgpbart', x, M)
}

symm_distance_matrix <- function(m1) {
    .Call('_mixgpbart_symm_distance_matrix', PACKAGE = 'mixgpbart', m1)
}

distance_matrix <- function(m1, m2) {
    .Call('_mixgpbart_distance_matrix', PACKAGE = 'mixgpbart', m1, m2)
}

